#!/usr/bin/env bash

pictures="$HOME/Pictures"

# If the ~/Pictures/wallpapers/<NIXOS_THEME> directory exists, select a random wallpaper.
if [[ -d "$pictures" && -d "$pictures/wallpapers" && -d "$pictures/wallpapers/$NIXOS_THEME" ]]; then
    names=$(find "$pictures/wallpapers/$NIXOS_THEME"/*.{jpg,png} -prune -print 2> /dev/null)
    if (( "$(echo "$names" | wc -l)" > 0 )); then
        selected=$(echo "$names" | shuf -n 1)
        ln -sf "$selected" "$pictures/wallpaper.png"
    fi
fi

# If the wallpaper is a symbolic link, remove it.
if [[ -h "$pictures/wallpaper.png" ]]; then
    rm "$pictures/wallpaper.png"
fi

# If no wallpaper is selected and a themed wallpaper is available, select it.
if [[ ! -e "$pictures/wallpaper.png" ]]; then
    if [[ -e "$pictures/wallpaper-$NIXOS_THEME.png" ]]; then
        ln -sf "$pictures/wallpaper-$NIXOS_THEME.png" "$pictures/wallpaper.png"
    fi
fi

# If a wallpaper exists, apply it.
if [[ -e "$pictures/wallpaper.png" ]]; then
    feh --no-fehbg --bg-fill "$pictures/wallpaper.png"
    betterlockscreen --update "$pictures/wallpaper.png" --fx dimblur
fi
