#!/usr/bin/env bash

#   first group         case a                case b          fourth group  sixth group
#   (filename)   (absolute w/ spaces)  (relative w/o spaces)   (line nr)    (column nr)
#       |               |                     |                   |              |
#       |+--------------+        +------------+        +----------+              |
#       ||                       |                     |         +---------------+
#       VV                       V                     V         V
REGEX='/(\/(\/?[ 0-9A-Za-z-._])+|(\/?[0-9A-Za-z-._])+):([0-9]+)(:([0-9]+))?/'

FILENAME=$(perl -n -e "$REGEX && print \$1" <<<"$1")
LINE=$(perl -n -e "$REGEX && print \$4" <<<"$1")
COLUMN=$(perl -n -e "$REGEX && print \$6" <<<"$1")

if [[ -z "$LINE" ]]; then
    LINE='0'
fi

if [[ -z "$COLUMN" ]]; then
    COLUMN='0'
fi

alacritty msg create-window \
    --working-directory "$PWD" \
    --command nvim -c "call cursor($LINE,$COLUMN)" "$PWD/$FILENAME"
